version: '3.8'
services:
  user-data:
    image: 'postgres:latest'
    container_name: user-data
    environment:
      - 'POSTGRES_DB=userdb'
      - 'POSTGRES_PASSWORD=user'
      - 'POSTGRES_USER=user'
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-auth-data:/var/lib/postgres-auth-data/data